env:
  - NOT_CRAN=true
language: r
cache: packages
r:
  - oldrel
  - release
  - devel
os:
  - linux
addons:
  apt:
    packages:
    - libcgal-dev
    - libglu1-mesa-dev
    - libgdal1-dev
after_success:
    - Rscript -e 'covr::codecov()'

